version: '3'

# http://people.oregonstate.edu/~chriconn/sites/docker_mongoDB/
# https://medium.com/faun/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile_client
        container_name: restaurants_client
        volumes: ['./client:/usr/src/app']
        restart: always
        ports:
            - '8080:8080'
        links:
            - server
    server:
        build:
            context: .
            dockerfile: Dockerfile_server
        container_name: restaurants_server
        volumes: ['./server:/usr/src/app']
        restart: always
        ports:
            - '5000:5000'
        links:
            - mongo
    mongo:
        image: mongo
        container_name: restaurants_mongo
        restart: always
        volumes:
            - ./db-data:/data/db
            - ./db-init:/docker-entrypoint-initdb.d
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_DATABASE: restaurants
            MONGO_INITDB_ROOT_USERNAME: restaurants
            MONGO_INITDB_ROOT_PASSWORD: restaurants
        networks:
            - default
    mongo-express:
        image: mongo-express
        container_name: restaurants_mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: restaurants
            ME_CONFIG_MONGODB_ADMINPASSWORD: restaurants
        networks:
        - default

networks:
    default:
