version: '3'

# http://people.oregonstate.edu/~chriconn/sites/docker_mongoDB/
# https://medium.com/faun/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile_client
        container_name: cronmap_client
        volumes: ['./client:/usr/src/app']
        restart: always
        ports:
            - '8080:8080'
        links:
            - server
    server:
        build:
            context: .
            dockerfile: Dockerfile_server
        container_name: cronmap_server
        volumes: ['./server:/usr/src/app']
        restart: always
        ports:
            - '5000:5000'
        links:
            - mongo
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        volumes:
            - ./db-data:/data/db
            - ./db-init:/docker-entrypoint-initdb.d
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_DATABASE: cronmap
            MONGO_INITDB_ROOT_USERNAME: cronmap
            MONGO_INITDB_ROOT_PASSWORD: cronmap
        networks:
            - default
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: cronmap
            ME_CONFIG_MONGODB_ADMINPASSWORD: cronmap
        networks:
        - default

networks:
    default:
